name: Release
on:
  workflow_dispatch:
jobs:
  release-bins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go install github.com/golang/mock/mockgen@v1.6.0
      - uses: actions/setup-node@v2.4.0
      - name: Build go binaries
        run: make release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "bin/*"
